---
- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Docker login 
  community.docker.docker_login:
    username: "{{ username }}"
    password: "{{ password }}"

- name: remove directory 
  file:
    path: /home/ubuntu/kube-deploy
    state: absent

- name: Clone a repo with separate git directory
  git:
    repo: https://github.com/suraj9741/kube-deploy.git
    dest: /home/ubuntu/kube-deploy

- name: see manifest file before change
  shell: cat kube-deploy/k8s/fask-app.yml
  register: displaylist

- name: show fask-app.yml file
  debug:
    msg: "{{displaylist.stdout_lines}}"

- name: Replace a image with laltest iamge
  replace:
    path: kube-deploy/k8s/fask-app.yml
    regexp: '(?<= image: )(.*)$'
    replace: 'suraj9741/koko:{{ tag }}'

- name: see manifest file after change
  shell: cat kube-deploy/k8s/fask-app.yml
  register: displaylist

- name: show fask-app.yml file
  debug:
    msg: "{{displaylist.stdout_lines}}"

- name: deploy application with the help of helm chart
  shell: "helm upgrade fask-app kube-deploy/mychart/ --set image.tag={{ tag }}"
  register: displaylist

- name: read the helm ouput
  debug:
    msg: "{{displaylist.stdout_lines}}"