apiVersion: apps/v1
kind: Deployment
metadata:
  name: fask-app
  namespace: default
spec:
  selector:
    matchLabels:
      run: fask-app
  replicas: 1
  template:
    metadata:
      labels:
        run: fask-app
      namespace: default
    spec:
      containers:
      - name: fask-app
        image: suraj9741/koko:test
        command: ["gunicorn",  "--bind", "0.0.0.0:5000", "app:app"]
        ports:
        - containerPort: 5000