apiVersion: v1
kind: Service
metadata:
  name: fask-app-5000
  labels:
    run: fask-app-5000
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30042
    protocol: TCP
  selector:
    run: fask-app