# An Ansible playbook to deploy the Perfios scripts project

- name: Update manifest file and push 
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true
  tags:
    - deploy
  roles:
    - role: update_manifestfile
